obj-$(CONFIG_MACH_AC8257) += recovery_mem.o
obj-$(CONFIG_AC8257_EARLY_PSTORE_CONSOLE) += early_pstore_console.o
obj-$(CONFIG_AC8257_BRINGUP_PANIC) += bringup_reboot.o
obj-$(CONFIG_JANCAR_GPIOS) += jancar_gpios.o
obj-$(CONFIG_AC8257_INPUT_BOOST) += ac8257_input_boost.o
ccflags-$(CONFIG_AC8257_INPUT_BOOST) += -I$(srctree)/drivers/misc/mediatek/base/power/include/ppm_v3
obj-$(CONFIG_ATC_METAZONE) += metazone.o
